version: 2.1

jobs:
  build_and_test:
    docker:
      - image: circleci/node:14
      - image: circleci/postgres:13
        environment:
          POSTGRES_PASSWORD: your_postgres_password  # Set your actual password here
    steps:
      - checkout

      # Build and test React project
      - run:
          name: Build and Test React Project
          command: |
            docker build -t rajamritsingh/react-test -f ./client/Dockerfile.dev ./client
            docker run -e CI=true rajamritsingh/react-test npm test

  build_and_push_docker:
    docker:
      - image: docker:20.10.10
    steps:
      - checkout

      # Build Docker images
      - run:
          name: Build Docker Images
          command: |
            docker build -t rajamritsingh/multi-client ./client
            docker build -t rajamritsingh/multi-nginx ./nginx
            docker build -t rajamritsingh/multi-server ./server
            docker build -t rajamritsingh/multi-worker ./worker

      # Push Docker images to Docker Hub
      - run:
          name: Push Docker Images
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
            docker push rajamritsingh/multi-client
            docker push rajamritsingh/multi-nginx
            docker push rajamritsingh/multi-server
            docker push rajamritsingh/multi-worker

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_test
      - build_and_push_docker:
          requires:
            - build_and_test
version: 2.1

jobs:
  build_and_test:
    docker:
      - image: circleci/node:14
      - image: circleci/postgres:13
        environment:
          POSTGRES_PASSWORD: postgres_password  # Set your actual password here
    steps:
      - checkout

      # Build and test React project
      - run:
          name: Build and Test React Project
          command: |
            docker build -t rajamritsingh/react-test -f ./client/Dockerfile.dev ./client
            docker run -e CI=true rajamritsingh/react-test npm test

  build_and_push_docker:
    docker:
      - image: docker:20.10.10
    steps:
      - checkout

      # Build Docker images
      - run:
          name: Build Docker Images
          command: |
            docker build -t rajamritsingh/multi-client ./client
            docker build -t rajamritsingh/multi-nginx ./nginx
            docker build -t rajamritsingh/multi-server ./server
            docker build -t rajamritsingh/multi-worker ./worker

      # Push Docker images to Docker Hub
      - run:
          name: Push Docker Images
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
            docker push rajamritsingh/multi-client
            docker push rajamritsingh/multi-nginx
            docker push rajamritsingh/multi-server
            docker push rajamritsingh/multi-worker

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_test
      - build_and_push_docker:
          requires:
            - build_and_test
